name: Sync Fork and Modify Content

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: "0 16 * * 1" # 每周一的16:00 UTC触发一次，相当于北京时间周一0:00

jobs:
  sync-and-modify:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保获取完整的提交历史

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

      # Step 3: Download and Rename Specific Files
      - name: Download and Rename Specific Files
        run: |
          mkdir -p rule-set
          curl -o rule-set/Hijacking.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/Hijacking.list"
          curl -o rule-set/ForceDirect.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/force-direct.list"
          curl -o rule-set/ForceProxy.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/force-proxy.list"
          curl -o rule-set/Apple.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/Apple.list"
          curl -o rule-set/MicroSoft.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/microsoft.list"
          curl -o rule-set/Telegram.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/Telegram.list"
          curl -o rule-set/Netease.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/media/netease.list"
          curl -o rule-set/Streaming.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/Streaming.list"
          curl -o rule-set/StreamingSE.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/StreamingSE.list"
          curl -o rule-set/Global.txt "https://cdn.jsdelivr.net/gh/SleepyHeeead/subconverter-config@master/ruleset/external/DivineEngine/Surge/Global.list"

      # Step 4: Modify .txt files in rule-set directory
      - name: Modify .txt Files in Rule-Set Directory
        run: |
          find rule-set -type f -name "*.txt" -exec sed -i '/IP-ASN/d' {} \;
          find rule-set -type f -name "*.txt" -exec sed -i '/PROCESS-NAME/d' {} \;
          find rule-set -type f -name "*.txt" -exec sed -i '/URL-REGEX/d' {} \;
          find rule-set -type f -name "*.txt" -exec sed -i '/USER-AGENT/d' {} \;
          find rule-set -type f -name "*.txt" -exec sed -i '/GEOIP/d' {} \;

      # Step 5: Check for changes and commit if any
      - name: Commit and Push Changes
        env:
          PARSERS_FOR_CLASH_ACTIONS_TOKEN: ${{ secrets.PARSERS_FOR_CLASH_ACTIONS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PARSERS_FOR_CLASH_ACTIONS_TOKEN }}@github.com/${{ github.repository }}
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Actions: 从上游同步并修改文件"
            git push origin main
          else
            echo "Actions: 上游没有需要修改的提交"
